name: GBA-butano-v8
on:
  push:
    branches:
    - master
jobs:
  build-GBA-butano:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Compile
      run: |
        cd ./examples/profiler
        make
    - name: Upload
      uses: actions/upload-artifact@v5
      with:
        name: GBA-butano
        path: |
          ./examples/profiler*.gba
